# Generated by Django 5.2.6 on 2026-04-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YugiohCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ygopro_id', models.BigIntegerField(unique=True)),
                ('konami_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('card_type', models.CharField(blank=True, max_length=150)),
                ('human_readable_card_type', models.CharField(blank=True, max_length=150)),
                ('frame_type', models.CharField(blank=True, max_length=150)),
                ('desc', models.TextField(blank=True)),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=150)),
                ('attribute', models.CharField(blank=True, max_length=100)),
                ('archetype', models.CharField(blank=True, max_length=200)),
                ('ygoprodeck_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YugiohCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_url_small', models.URLField(blank=True)),
                ('image_url_cropped', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='YugiohCardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=255)),
                ('set_code', models.CharField(max_length=100)),
                ('set_rarity', models.CharField(blank=True, max_length=150)),
                ('set_rarity_code', models.CharField(blank=True, max_length=50)),
                ('set_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YugiohCardTypeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('card_description', models.TextField(blank=True)),
                ('seller_description', models.TextField(blank=True)),
                ('archetype', models.CharField(blank=True, max_length=100)),
                ('rarity', models.CharField(blank=True, max_length=100)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('attribute', models.CharField(blank=True, max_length=50)),
                ('set_name', models.CharField(blank=True, max_length=150)),
                ('set_code', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('light_played', 'Light Played'), ('moderate_played', 'Moderate Played'), ('heavy_played', 'Heavy Played'), ('damaged', 'Damaged')], default='near_mint', max_length=20)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('seller_images', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.cardcategory')),
            ],
        ),
    ]
