# Generated by Django 5.2.6 on 2026-04-03 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardlisting',
            name='yugioh_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cards.yugiohcard'),
        ),
        migrations.AddField(
            model_name='yugiohcardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.yugiohcard'),
        ),
        migrations.AddField(
            model_name='yugiohcardset',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='cards.yugiohcard'),
        ),
        migrations.AddField(
            model_name='cardlisting',
            name='yugioh_card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cards.yugiohcardset'),
        ),
        migrations.AddField(
            model_name='yugiohcardtypeline',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typelines', to='cards.yugiohcard'),
        ),
    ]
