# Generated by Django 5.2.6 on 2026-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlisting',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
