# Generated by Django 5.2.6 on 2026-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardlisting_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='yugiohcardset',
            constraint=models.UniqueConstraint(fields=('card', 'set_code', 'set_rarity'), name='unique_card_version'),
        ),
    ]
